server.port=8084
spring.application.name=EMAIL-SERVICE


# Brevo SMTP (backup - commented out)
spring.mail.host=${EMAIL_HOST_BREVO:smtp-relay.brevo.com}
spring.mail.port=${EMAIL_PORT_BREVO:2525}
spring.mail.username=${EMAIL_USER_BREVO}
spring.mail.password=${EMAIL_PASS_BREVO}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.default-encoding=UTF-8
app.email.from-address=${EMAIL_SENDER_BREVO}
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
app.frontend-url=http://localhost:5173

# Kafka Consumer
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=email-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

management.endpoints.web.exposure.include=*